# Generated by Django 3.2.4 on 2022-07-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('civil_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('party_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.party')),
                ('family_responsibilities', models.IntegerField()),
                ('type_customer', models.CharField(max_length=2)),
                ('residence_date', models.DateField()),
            ],
            bases=('api.party',),
        ),
    ]
